# Generated by Django 3.1.7 on 2021-04-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210427_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ratings_point',
            field=models.FloatField(default=0.0, max_length=2, verbose_name='Rating Point'),
        ),
    ]
