# Generated by Django 3.1.7 on 2021-04-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_ratings_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_joined',
            new_name='create_at',
        ),
    ]
